 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servergui;

import java.io.EOFException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.awt.event.*;
import java.awt.*;
import java.net.Inet4Address;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.sql.Timestamp;


/**
 *
 * @author Saad Afzaal
 */
public class Server extends javax.swing.JFrame {

    /**
     * Creates new form Server
     */
    
    private ObjectOutputStream output;
    private ObjectInputStream input;
    private ServerSocket server;
    private Socket connection;
    private String Username;
    private String Receivername;
    private int serverPort;
    private String UserNo;
    private String ReceiverNo;
    
    public Server(String username , String receivername , String userNo , String receiverNo) {
        initComponents();
        
        userText.setEditable(false);
        
        Username = username;
        Receivername = receivername;
        UserNo = userNo;
        ReceiverNo = receiverNo;
        
        AddressTxtBox.setEditable(false);
        
        PortTxtBox.setEditable(false);
        
        setTitle(Receivername);
        
        get_chatting();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatWindow = new javax.swing.JTextArea();
        Close_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AddressTxtBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PortTxtBox = new javax.swing.JTextField();
        Connect_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server Area");

        userText.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        userText.setName("userText"); // NOI18N
        userText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextActionPerformed(evt);
            }
        });

        chatWindow.setEditable(false);
        chatWindow.setColumns(20);
        chatWindow.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        chatWindow.setRows(5);
        chatWindow.setName("chatWindow"); // NOI18N
        jScrollPane1.setViewportView(chatWindow);

        Close_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Close_Button.setText("X");
        Close_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_ButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("IPAddress :");

        jLabel2.setText("Port :");

        Connect_Button.setText("Connect");
        Connect_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Connect_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userText)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PortTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Connect_Button)
                .addGap(18, 18, 18)
                .addComponent(Close_Button))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Close_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(AddressTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(PortTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Connect_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextActionPerformed
        // TODO add your handling code here:
        
        sendMessage(evt.getActionCommand());
        userText.setText("");
        
        DateFormat dateFormat = new SimpleDateFormat("E h:mm a");
        Date date = new Date();
                
        showMessage("\n" + dateFormat.format(date) + "\n");
    }//GEN-LAST:event_userTextActionPerformed

    private void Close_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_ButtonActionPerformed
        // TODO add your handling code here:
        
            dispose();
            
            try
            { 
                //Chat c = new Chat(Username);
                //c.setVisible(true);
               // c.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
                
                server.close();
                closeCrape();                  
            }
            catch(IOException ioException)
            {
                JOptionPane.showMessageDialog(null , ioException.getMessage());
                ioException.printStackTrace();
            }
            
            //this.Close_ButtonActionPerformed(evt);
            //setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            //this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
            
            //System.exit(0);
            //WindowEvent winClosingEvent = new WindowEvent(this , WindowEvent.WINDOW_CLOSING);
            //Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
            //this.setVisible(false);
    }//GEN-LAST:event_Close_ButtonActionPerformed

    private void Connect_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Connect_ButtonActionPerformed
        // TODO add your handling code here:
        
        Thread serverThread = new Thread(new Runnable()
        {
           public void run()
           {
               try
               {
                    String url = "jdbc:derby://localhost:1527/MyDataBase";
                    String uName = "Saad";
                    String uPass= "03214061595";

                    Connection con = DriverManager.getConnection(url , uName , uPass);
                    
                    String sql4 = "SELECT * FROM CONTACTS where PHONENO = '" + ReceiverNo + "' AND USER_PHONENO = '" + UserNo + "'";
                    Statement stat4 = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
                    ResultSet rs4 = stat4.executeQuery(sql4);
                            
                    rs4.absolute(1);
                    int Port = rs4.getInt("PORT");
                
                    stat4.close();
                    rs4.close();
                    
                    try
                    {
                        String IP_Address = Inet4Address.getLocalHost().getHostAddress();
                        
                        String sql3 = "SELECT * FROM CONTACTS where (PHONENO = '" + ReceiverNo + "' AND USER_PHONENO = '" + UserNo + "') OR PHONENO = '" + UserNo + "' AND USER_PHONENO = '" + ReceiverNo + "'";
                        Statement stat3 = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                        ResultSet rs3 = stat3.executeQuery(sql3);
                    
                        while(rs3.next())
                        {
                            rs3.updateString("IPADDRESS", IP_Address);
                            rs3.updateRow(); 
                        }
                        
                        stat3.close();
                        rs3.close();
                    }
                    catch(IOException ie)
                    {
                        JOptionPane.showMessageDialog(null , ie.getMessage());
                    }
               
                    PortTxtBox.setText(Integer.toString(Port));
                    
                    try
                    { 
                        serverPort = Port;
                        startRunnig();
                    }
                    catch(Exception ex)
                    {
                        JOptionPane.showMessageDialog(null , "Cannot create Server on port " + Port);
                    }
                }
                catch(SQLException ex)
                {
                    JOptionPane.showMessageDialog(null , ex.getMessage());
                }
            }
        });
             
        serverThread.start();
      
        // wait a bit
        try
        {
            Thread.sleep(1000);
        }
        catch(Exception e)
        {
            
        }  
    }//GEN-LAST:event_Connect_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void get_chatting()
    {
        Thread serverThread = new Thread(new Runnable()
        {
           public void run()
           {
                try
                {
                    String url = "jdbc:derby://localhost:1527/MyDataBase";
                    String uName = "Saad";
                    String uPass= "03214061595";

                    Connection con = DriverManager.getConnection(url , uName , uPass);
            
                    String sql = "SELECT * FROM CHATTING_MESSAGES where (SENDER_RECEIVER_CONTACTNO_1 = '" + UserNo + "' AND SENDER_RECEIVER_CONTACTNO_2 = '" + ReceiverNo + "') OR (SENDER_RECEIVER_CONTACTNO_1 = '" + ReceiverNo + "' AND SENDER_RECEIVER_CONTACTNO_2 = '" + UserNo + "') ORDER BY ID ASC";
                    Statement stat = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
                    ResultSet rs = stat.executeQuery(sql);
                            
                    while(rs.next())
                    {
                        String msg = rs.getString("MESSAGES");
                        Date date = rs.getTimestamp("Date_Time");
                
                        DateFormat dateFormat = new SimpleDateFormat("E h:mm a");
                
                        showMessage("\n" + msg);
                
                        showMessage("\n" + dateFormat.format(date) + "\n");
                    }
            
                    stat.close();
                    rs.close();
                }
                catch (SQLException se)
                {
                    JOptionPane.showMessageDialog(null , se.getMessage());
                }
            }
        });
             
        serverThread.start();
    }
    
    public void startRunnig()
    {
        try
        {
            server = new ServerSocket(serverPort , 100);
            while(true)
            {
                try
                {
                    waitForConnection();
                    setupStreams();
                    whileChatting();
                }
                catch(EOFException eofException)
                {
                    showMessage("\n\n" + Username +" ended the connection!");
                }
                finally
                {
                    closeCrape();
                }
            }
        }
        catch(IOException ioException)
        {
            ioException.printStackTrace();
        }
    }
    
    private void waitForConnection() throws IOException
    {
        showMessage("Waiting for connection...\n");
        connection = server.accept();
        showMessage("Now connected to " + connection.getInetAddress().getHostAddress());
        AddressTxtBox.setText(connection.getInetAddress().getHostAddress());
        AddressTxtBox.setEditable(false);
        PortTxtBox.setEditable(false);
        Connect_Button.setEnabled(false);
    }
    
    private void setupStreams() throws IOException
    {
        output = new ObjectOutputStream(connection.getOutputStream());
        output.flush();
        input = new ObjectInputStream(connection.getInputStream());
        showMessage("\nStreams are now setup!\n");
    }
    
    private void whileChatting() throws IOException
    {           
        String message = "You are now connected!";
        sendMessage(message);
        ableToType(true);
        do
        {
            try
            {
                message = (String) input.readObject();
                showMessage("\n" + message);
                
                DateFormat dateFormat = new SimpleDateFormat("E h:mm a");
                Date date = new Date();
                
                showMessage("\n" + dateFormat.format(date) + "\n");
                
                String msg = message;
     
                try
                {
                    String url = "jdbc:derby://localhost:1527/MyDataBase";
                    String uName = "Saad";
                    String uPass= "03214061595";

                    Connection con = DriverManager.getConnection(url , uName , uPass);
            
                    String sql = "SELECT * FROM COUNTER";
                    Statement stat = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
                    ResultSet rs = stat.executeQuery(sql);
                            
                    rs.absolute(1);
                    String count = rs.getString("MSG_COUNTER");
                
                    stat.close();
                    rs.close();
                    
                    long Count = Long.valueOf(count).longValue();
                
                    Count++;
                    
                    String sql1 = "SELECT * FROM CHATTING_MESSAGES";
                    Statement stat1 = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                    ResultSet rs1 = stat1.executeQuery(sql1);
            
                    rs1.moveToInsertRow();
                    rs1.updateLong("ID",Count);
                    rs1.updateString("SENDER_RECEIVER_NAME_1", Username);
                    rs1.updateString("SENDER_RECEIVER_CONTACTNO_1", UserNo);
                    rs1.updateString("Messages", msg);
                    rs1.updateString("SENDER_RECEIVER_NAME_2", Receivername);
                    rs1.updateString("SENDER_RECEIVER_CONTACTNO_2", ReceiverNo);
                    rs1.updateTimestamp("DATE_TIME", new Timestamp(date.getTime()));
                    rs1.insertRow(); 
                
                    stat1.close();
                    rs1.close();
                    
                    String sql2 = "SELECT * FROM COUNTER";
                    Statement stat2 = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                    ResultSet rs2 = stat2.executeQuery(sql2);
                    
                    String C = Long.toString(Count);
                    
                    rs2.absolute(1);
                    rs2.updateString("MSG_COUNTER", C);
                    rs2.updateRow(); 
                    
                    stat2.close();
                    rs2.close();
                }
                catch (SQLException se)
                {
                    JOptionPane.showMessageDialog(null , se.getMessage());
                }        
                
                //JOptionPane.showMessageDialog(null , Username + UserNo + msg + Receivername + ReceiverNo);
            }
            catch(ClassNotFoundException classNotFoundException)
            {
                showMessage("\nIdk wtf that user sent!");
            }
        }while(!message.equals(Receivername + " - END"));
    }
    
    private void closeCrape()
    {
        showMessage("\n\nClosing connection...\n");
        ableToType(false);
        try
        {
            output.close();
            input.close();
            connection.close();
        }
        catch(IOException ioException)
        {
            ioException.printStackTrace();
        }
    }
    
    private void sendMessage(String message)
    {
        try
        {
            output.writeObject(Username + " - " + message);
            output.flush();
            showMessage("\n" + Username + " - " + message);
        }
        catch(IOException ioException)
        {
            chatWindow.append("\nERROR: DUDE I can't send that message!");
        }
    }
    
    private void showMessage(final String text)
    {
        SwingUtilities.invokeLater(
        new Runnable()
        {
            public void run()
            {
                chatWindow.append(text);
            }
        }
        );
    }
    
    private void ableToType(final boolean tof)
    {
         SwingUtilities.invokeLater(
        new Runnable()
        {
            public void run()
            {
                userText.setEditable(tof);
            }
        }
        );
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server("Server" , "My Server" , "###" , "###").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTxtBox;
    private javax.swing.JButton Close_Button;
    private javax.swing.JButton Connect_Button;
    private javax.swing.JTextField PortTxtBox;
    private javax.swing.JTextArea chatWindow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables
}
