/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servergui;

import java.awt.Color;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.net.Inet4Address;

/**
 *
 * @author Amjad Afzaal
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        
        InternalFrame.getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        InternalFrame = new javax.swing.JInternalFrame();
        UsernameTxtBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PasswordTxtBox = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        GoBack_Button = new javax.swing.JButton();
        Login_Button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SignUp");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("SignUp");

        InternalFrame.setBackground(new java.awt.Color(255, 255, 255));
        InternalFrame.setVisible(true);

        UsernameTxtBox.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        UsernameTxtBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Enter Username  :");

        PasswordTxtBox.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        PasswordTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTxtBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Enter Password  :");

        GoBack_Button.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        GoBack_Button.setText("GoBack");
        GoBack_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBack_ButtonActionPerformed(evt);
            }
        });

        Login_Button.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Login_Button.setText("Login");
        Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InternalFrameLayout = new javax.swing.GroupLayout(InternalFrame.getContentPane());
        InternalFrame.getContentPane().setLayout(InternalFrameLayout);
        InternalFrameLayout.setHorizontalGroup(
            InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternalFrameLayout.createSequentialGroup()
                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InternalFrameLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(Login_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GoBack_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InternalFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PasswordTxtBox, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(UsernameTxtBox))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InternalFrameLayout.setVerticalGroup(
            InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternalFrameLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login_Button)
                    .addComponent(GoBack_Button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\B -Z -U\\6th Semester\\NetBeans Java Programes\\ServerClientGUI\\src\\servergui\\signup.jpg")); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InternalFrame)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoBack_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBack_ButtonActionPerformed
        // TODO add your handling code here:
        
        ChatSoft cs = new ChatSoft();
        cs.setVisible(true);
        cs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_GoBack_ButtonActionPerformed

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
        // TODO add your handling code here:
        
        String username = UsernameTxtBox.getText();
        String password = PasswordTxtBox.getText();
        
        if(username.equals("") || password.equals(""))
        {
            JOptionPane.showMessageDialog(null , "Username and Password must Required!");
        }
        else
        {
            try
            {
                String url = "jdbc:derby://localhost:1527/MyDataBase;";
                String uName = "Saad";
                String uPass= "03214061595";
                
                Connection con = DriverManager.getConnection(url , uName , uPass);
               
                String sql = "SELECT * FROM ACCOUNTS where USERNAME = '" + username +"' and PASSWORD = '" + password +"'";
                Statement stat = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
                ResultSet rs = stat.executeQuery(sql);
                
                rs.first();
                String Username = rs.getString("USERNAME");
                String Password = rs.getString("PASSWORD");
                
                if(Username.equals("") || Password.equals(""))
                {
                    JOptionPane.showMessageDialog(null , "Invalid Username or Password!");
                }
                else
                {
                    try
                    {
                        String sql1 = "SELECT * FROM SESSION where USERNAME = '" + username + "'";
                        Statement stat1 = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
                        ResultSet rs1 = stat1.executeQuery(sql1);
            
                        rs1.first();
                        boolean Session_id = rs1.getBoolean("SESSION_ID");
                        
                        if(Session_id == true)
                        {
                            JOptionPane.showMessageDialog(null , "Cannot Loggin You already Loggin from your account!");
                        }
                        else
                        {
                            String sql2 = "SELECT * FROM SESSION where USERNAME = '" + Username + "'";
                            Statement stat2 = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                            ResultSet rs2 = stat2.executeQuery(sql2);
            
                            rs2.first();
                            rs2.updateBoolean("SESSION_ID", true);
                            rs2.updateRow();
                            
                            /*String sql3 = "SELECT * FROM LOGGINCHECK";
                            Statement stat3 = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                            ResultSet rs3 = stat3.executeQuery(sql3);
            
                            rs3.moveToInsertRow();
                            rs3.updateString("USERNAME",username);
                            rs3.updateString("ISLOGGIN", "Yes");
                            rs3.insertRow();
                            
                            stat3.close();
                            rs3.close();*/
                            
                            MainPage mp = new MainPage(Username);
                            mp.setVisible(true);
                            mp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.setVisible(false);
                        }
                    }
                    catch (SQLException se)
                    {
                        JOptionPane.showMessageDialog(null , se.getMessage());
                    }        
                }
            }
            catch(SQLException se)
            {
                JOptionPane.showMessageDialog(null , "Invalid Username or Password!\n" /*se.getMessage()*/);
            }     
        }
    }//GEN-LAST:event_Login_ButtonActionPerformed

    private void PasswordTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTxtBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoBack_Button;
    private javax.swing.JInternalFrame InternalFrame;
    private javax.swing.JButton Login_Button;
    private javax.swing.JPasswordField PasswordTxtBox;
    private javax.swing.JTextField UsernameTxtBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
